### ISSUE TITLE
Create a Report on LLM Research Findings

### ISSUE THREAD

**Issue by grayJiaaoLi** [amosproj/amos2024ss08-cloud-native-llm#21]
## User story
1. As a Software Engineer
2. I want to summarise the research findings of LLMs in a report
3. So that the team can finalise a decision on the open-source LLM

## Acceptance criteria
* The report covers the advantages and limitations of each candidates
* It is based on the results of evaluation and selection process
* It makes a clear decision for the most suitable LLM (ranking of the selection candidates)
* And states the reasons of the final decision
* The selected LLM satisfies the baseline of requirements:
  * The LLM is available under a permissive license (MIT/Apache 2.0)
  * English must be supported
  * We can Fine-tune the model using the structured dataset we obtained

## DoD general criteria
* Feature has been fully implemented
* Feature has been merged into the mainline
* All acceptance criteria were met
* Product owner approved features
* All tests are passing
* Developers agreed to release

**Comment by christianwielenberg** [comment]
# Report on LLM Research Findings

In our project we want to fine tune a Large Language Model so that it can provide better question answering performance about the projects of the Cloud Native Computing Foundation. 

For that it should be able to process data in a "prompt - response" format. 


## Considerations

There are 5 things that need to be considered:
1. The model should be able to process data in a "prompt - response" format.
2. The model should be licensed under an open license like MIT/Apache
3. The model should have good performance in the most common LLM benchmarks.
4. As we only have access to limited resources, our model should not be larger than necessary
5. The available documentation for the model
The first 2 considerations are an absolute requirement and are absolutely necessary so that we can finish the project.
The 3rd and 4th considerations are more flexible as we ideally want very good performance at an acceptable size.
The last consideration is also very important to us, as it likely makes it easier to create a transfer learning script.

## Models

We have considered the following models:
1. Gemma
2. Llama3
3. Llama3-instruct
4. Mistral
5. Calme-7B-Instruct-v0.9
6. Mixtral-8x22b-Instruct

In the following we will explain the models shortly and provide our assessment for the specific models.

### Gemma
Gemma is an open LLM family developed by Google. It comprises of two different versions the 2 billion and 7 billion parameter version. The first one is designed for the use with CPUs while the latter one is designed for the use with GPUs. It also has Instruction tuned versions but these seem to perform significantly worse. 
Gemma is developed under the Gemma license, which is an open license.
It processes data in a "prompt - response" format. 
We want to use the 7b parameter version which has good performance in the most important benchmarks as you can see in the table below. 
There are a lot of resources on how to use it.
### Llama3
Llama is an open LLM family developed by Meta. It has a 70b version and an 8b parameter Version. It has instruction tuned and pre trained variants. It is developed for the use with GPUs.
Llama is developed under the Llama license, which is an open license.
It processes data in a "prompt - response" format. 
We would consider using all of the Llama3 models, as they all full fill our requirements.
The Benchmark results can be seen in the table below.
There are a lot of resources on how to use it.
### Mistral

Mistral-AI has developed an open source model family that comprises of 3 different models:
One 7b parameter base model, as 8x7b parameter mixture model and a 8x22b parmeter mixture model. These models are available as pre trained and instruction fine tuned. It is developed for the use with GPUs and is developed under the apache 2.0 license. This is an open license.
We would consider using all of the Mistral models, as they all full fill our requirements.
The Benchmark results can be seen in the table below.
There might be a slight lack of resources when using this model. Both Gemma and Llama seemed to have more resources.

| Model                  | Model size | HuggingFace Avg | ARC   | HellaSwag | MMLU  |
| ---------------------- | ---------- | --------------- | ----- | --------- | ----- |
| Gemma                  | 7b         | 64.3            | 61    | 82.5      | 66    |
| Llama3                 | 8b         | 62.6            | 59.5  | 82.1      | 66.7  |
| Llama3-instruct        | 70b        | 77.8            | 71.42 | 85.7      | 80    |
| Llama3-instruct        | 8b         | 66.8            | 60.7  | 78.5      | 67.07 |
| Mistral-Instruct       | 7b         | 61              | 60    | 83        | 64    |
| Mistral-8x7b-Instruct  | 56b        | 72.6            | 70.2  | 87.6      | 71.2  |
| Mixtral-8x22b-Instruct | 141b       | 79.1            | 72.7  | 89        | 77.7  |

## Conclusion

**Comment by christianwielenberg** [comment]
Can we close this?
@dominic0df
